### ISSUE TITLE
update readme with common app documentation 

### ISSUE THREAD

**Issue by keighrim** [clamsproject/apps#21]
Currently app documentation is spread over individual app repositories, and we want a centralized place to hold documentation about common behaviors of apps.

**Comment by marcverhagen** [comment]
I think it is okay for the documentation to live with the code on individual repositories, as long as there is some commonality in how we set up the README or HOWTO file. And I think the central place would be the appdirectpry, which would copy the documentation.

But I do think that a write up on the common behavior is a good thing, we could point to that from each repo and be able to be real short in the repo, relying on the common document to give some background.

**Comment by keighrim** [comment]
A generic CLAMS app readme is not included as a part of "app template" in the SDK. Now we need to decide where that readme is published as a webpage, easily accessible to users.
