### ISSUE TITLE
dbpedia-spotlight wrapper

### ISSUE THREAD

**Issue by keighrim** [clamsproject/apps#26]
As a subtask of https://github.com/clamsproject/clams-apps/issues/12, we have tried to wrap this NE linker app [DBpedia Spotlight](https://www.dbpedia-spotlight.org/) ( [GH repo](https://github.com/dbpedia-spotlight/dbpedia-spotlight-model) ) as a CLAMS app in the past, twice. However, both attempts failed to deliver a standalone app that runs the dbp-spotlight as a local server and in completely contained in a single container image, which is (un-documented) requirement of an CLAMS app. 

To achieve the goal, here's what needs to be done; 
* Building jar and running it as a local server
* Writing python code to send HTTP requests the local server and get the result
* Making the python code to be able to handle existing NER annotations (in MMIF format) 
* Making the python code to re-wrap the output from spotlight tool into a MMIF format (@JinnyViboonlarp  has written code for this; consulting with her might be a good idea)

And then, once we saw the above is possible
* Wrap the python code into a CLAMS app, using clams-python SDK
* Wrapping the CLAMS app and the jar into a single docker image that runs standalone

This issue is done when 
* such a wrapper is written and published as a codebase under clamsproject GH ans as a container image under clamsproject GHCR, OR
* the dpb-spotlight is proven unusable as a CLAMS app.

**Comment by keighrim** [comment]
@wricketts if there's been any update, could you give us some written notes (as a comment here) before our meeting tomorrow?

**Comment by wricketts** [comment]
Sure, here is the status so far:

- [X] Building jar and running it as a local server 
- [X] Writing python code to send HTTP requests the local server and get the result
- [ ] Making the python code to be able to handle existing NER annotations (in MMIF format)

I wrote code assuming the input mmifs will have views with NER annotations. Mmif files that I generate from sample text files don't have these. I was wondering if there was somewhere I could access mmif files that already have these annotations, so I can test that this works?

**Comment by keighrim** [comment]
resolved via #81.
